### ISSUE TITLE
공지 커맨드 수정쩜

### ISSUE THREAD

**Issue by rookieman88** [ReMac720Studio/MilkBot#1]
아됴띠 https://github.com/rookieman88/DiscordJs-NoticeBot 버그 업뎃한지 999999999년이 지났는데 아직도 오류나는 코드를 쓰고 계시다니,, 팀 멜론 팀원들 아이디도 관리자로 좀 넣고 좀,,

**Comment by rookieman88** [comment]
아 토큰도 삭제쩜

**Comment by ReMac720Studio** [comment]
토큰 삭제 완료. 공지는 호스팅때문에 좀 미룰게요;;
